SET IDENTITY_INSERT [dbo].[Countries] ON
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (1, N'Great Britain', N'GB')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (2, N'Ireland', N'IE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (3, N'U.S.A.', N'US')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (4, N'France', N'FR')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (5, N'Italy', N'IT')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (6, N'Malta', N'MT')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (7, N'Portugal', N'PT')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (8, N'Spain', N'ES')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (9, N'Belgium', N'BE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (10, N'Luxembourg', N'LU')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (11, N'Netherlands', N'NL')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (12, N'Frisia', N'FY')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (13, N'Germany', N'DE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (14, N'Austria', N'AT')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (15, N'Swiss', N'CH')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (16, N'Iceland', N'IS')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (17, N'Denmark', N'DK')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (18, N'Norway', N'NO')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (19, N'Sweden', N'SE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (20, N'Finland', N'FI')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (21, N'Estonia', N'EE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (22, N'Latvia', N'LV')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (23, N'Lithuania', N'LT')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (24, N'Poland', N'PL')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (25, N'Czech Republic', N'CZ')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (26, N'Slovakia', N'SK')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (27, N'Hungary', N'HU')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (28, N'Romania', N'RO')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (29, N'Bulgaria', N'BG')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (30, N'Bosnia and Herzegovina', N'BA')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (31, N'Croatia', N'HR')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (32, N'Kosovo', N'KV')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (33, N'Macedonia', N'MK')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (34, N'Montenegro', N'ME')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (35, N'Serbia', N'RS')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (36, N'Slovenia', N'SI')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (37, N'Albania', N'AL')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (38, N'Greece', N'GR')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (39, N'Russia', N'RU')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (40, N'Belarus', N'BY')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (41, N'Moldova', N'MD')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (42, N'Ukraine', N'UA')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (43, N'Armenia', N'AM')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (44, N'Azerbaijan', N'AZ')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (45, N'Georgia', N'GE')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (46, N'Kazakhstan', N'KZ')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (47, N'Turkey', N'TR')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (48, N'Arabia/Persia', N'FA')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (49, N'Israel', N'IL')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (50, N'China', N'CN')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (51, N'India/Sri Lanka', N'IN')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (52, N'Japan', N'JP')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (53, N'Korea', N'KR')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (54, N'Vietnam', N'VN')
INSERT INTO [dbo].[Countries] ([Id], [Name], [CountryCode]) VALUES (55, N'other countries', NULL)
SET IDENTITY_INSERT [dbo].[Countries] OFF
